import { EPower } from './enums';
import { ICardVariant } from './types';

export const CARD_VARIANTS: ICardVariant[] = [
  { number: 1, power: EPower.MoveUpByTwo },
  { number: 2, power: EPower.RemoveTop },
  { number: 68, power: EPower.MoveDownByTwo },
  { number: 47, power: EPower.MoveUpByTwo },
  { number: 17, power: EPower.SwapThroughOne },
  { number: 66, power: EPower.MoveUpByTwo },
  { number: 41, power: EPower.RemoveBottom },
  { number: 13, power: EPower.RemoveBottom },
  { number: 29, power: EPower.MoveUpByTwo },
  { number: 74, power: EPower.RemoveMiddle },
  { number: 52, power: EPower.SwapNeighbours },
  { number: 14, power: EPower.Protect },
  { number: 46, power: EPower.RemoveMiddle },
  { number: 83, power: EPower.RemoveBottom },
  { number: 57, power: EPower.MoveUpByTwo },
  { number: 42, power: EPower.Protect },
  { number: 48, power: EPower.RemoveBottom },
  { number: 37, power: EPower.RemoveTop },
  { number: 58, power: EPower.RemoveTop },
  { number: 71, power: EPower.SwapNeighbours },
  { number: 43, power: EPower.SwapNeighbours },
  { number: 39, power: EPower.RemoveMiddle },
  { number: 60, power: EPower.RemoveMiddle },
  { number: 24, power: EPower.SwapNeighbours },
  { number: 12, power: EPower.MoveDownByTwo },
  { number: 32, power: EPower.RemoveMiddle },
  { number: 59, power: EPower.MoveDownByTwo },
  { number: 79, power: EPower.RemoveTop },
  { number: 19, power: EPower.MoveUpByTwo },
  { number: 25, power: EPower.RemoveMiddle },
  { number: 82, power: EPower.SwapThroughOne },
  { number: 55, power: EPower.RemoveBottom },
  { number: 33, power: EPower.SwapNeighbours },
  { number: 67, power: EPower.RemoveMiddle },
  { number: 5, power: EPower.SwapNeighbours },
  { number: 75, power: EPower.MoveUpByTwo },
  { number: 54, power: EPower.SwapThroughOne },
  { number: 23, power: EPower.RemoveTop },
  { number: 22, power: EPower.MoveDownByTwo },
  { number: 44, power: EPower.RemoveTop },
  { number: 16, power: EPower.RemoveTop },
  { number: 50, power: EPower.MoveDownByTwo },
  { number: 21, power: EPower.Protect },
  { number: 49, power: EPower.Protect },
  { number: 76, power: EPower.RemoveBottom },
  { number: 8, power: EPower.SwapThroughOne },
  { number: 31, power: EPower.MoveDownByTwo },
  { number: 35, power: EPower.Protect },
  { number: 9, power: EPower.RemoveTop },
  { number: 15, power: EPower.SwapNeighbours },
  { number: 30, power: EPower.RemoveTop },
  { number: 61, power: EPower.SwapNeighbours },
  { number: 53, power: EPower.RemoveMiddle },
  { number: 63, power: EPower.Protect },
  { number: 6, power: EPower.RemoveBottom },
  { number: 80, power: EPower.SwapNeighbours },
  { number: 72, power: EPower.RemoveTop },
  { number: 7, power: EPower.Protect },
  { number: 84, power: EPower.Protect },
  { number: 26, power: EPower.SwapThroughOne },
  { number: 77, power: EPower.Protect },
  { number: 70, power: EPower.Protect },
  { number: 51, power: EPower.RemoveTop },
  { number: 3, power: EPower.MoveDownByTwo },
  { number: 81, power: EPower.RemoveMiddle },
  { number: 11, power: EPower.RemoveMiddle },
  { number: 18, power: EPower.RemoveMiddle },
  { number: 64, power: EPower.SwapThroughOne },
  { number: 65, power: EPower.RemoveTop },
  { number: 4, power: EPower.RemoveMiddle },
  { number: 69, power: EPower.RemoveBottom },
  { number: 20, power: EPower.RemoveBottom },
  { number: 10, power: EPower.MoveUpByTwo },
  { number: 62, power: EPower.RemoveBottom },
  { number: 40, power: EPower.MoveDownByTwo },
  { number: 38, power: EPower.MoveUpByTwo },
  { number: 28, power: EPower.Protect },
  { number: 78, power: EPower.MoveDownByTwo },
  { number: 27, power: EPower.RemoveBottom },
  { number: 34, power: EPower.RemoveBottom },
  { number: 36, power: EPower.SwapThroughOne },
  { number: 45, power: EPower.SwapThroughOne },
  { number: 56, power: EPower.Protect },
  { number: 73, power: EPower.SwapThroughOne },
];

export const CARD_VARIANTS_MAP: Record<number, ICardVariant> = CARD_VARIANTS.reduce(
  (acc, cardVariant) => {
    acc[cardVariant.number] = cardVariant;
    return acc;
  },
  {} as Record<number, ICardVariant>
);
